tarea 3
IA-UNISON/tarea03-Algoritmos-Geneticos pull request #15
Opened 2017-09-28 04:58 UTC by Huguez

2017-11-01 17:18 UTC, juliowaissman requested changes
Muy bien!

100

2017-11-01 17:18 UTC, juliowaissman commented on genetico_tarea.py
> +        return self.problema.costo( individuo )
La adaptación debe de ser una función decreciente respecto al costo

2017-11-01 17:18 UTC, juliowaissman commented on genetico_tarea.py
> +        #Torneo de padres
Original, muy bien!

2017-11-01 17:18 UTC, juliowaissman commented on genetico_nreinas.py
> +    #
Ten cuidado: 200 * 100 = 20,000 individuos revisados, para 16 reinas.

2017-11-01 17:18 UTC, juliowaissman commented on genetico_nreinas.py
> +
¿Como en ambos casos las conclusiones son completamente contrarias' No tiene mucho sentido, a menos que me justifiques porqué crees que pasa esto.

2017-11-03 17:57 UTC, Huguez commented on genetico_nreinas.py
> +
en ese momento me parecian pocos individuso por que  tambien intente con 500 y 1000 individuos
fue error mio debi poner eso, pero despues platicando con mis compañeros me di cuenta que estaba exagerando con mi poblacion.

2023-11-21 03:10 UTC, closed without merging